ASP.NETCoreIdentityCustom/Models/Feallesbase.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;


namespace Bornholm_Slægts.Models
{

    public class Feallesbase
    {
        [Key]
        public int ID { get; set; }
        public string? AvisTypeID { get; set; }

        public DateTime? Avisdato { get; set; }
        public string? Efternavn { get; set; }
     
        public string? Fornavne { get; set; }

        public DateTime? Foedt { get; set; }
        public string? Alder { get; set; }
        public string? Doebenavn { get; set; }
        public string? Erhverv { get; set; }
        public string? Adresser { get; set; }
        public string? SognID { get; set; }
        public string? TidlBopael { get; set; }

        public DateTime? Doedsdato { get; set; }

        public DateTime? Begravelsesdato { get; set; }
        public string? Begravelsessted { get; set; }
        public string? Efterladte { get; set; }
        public string? FlereDoedsannoncer { get; set; }
        public string? AndreDataFraAnnoncen { get; set; }
        public string? Oegenavne { get; set; }

        public DateTime? Nekrolog { get; set; }

        public DateTime? Mindeord { get; set; }

        public DateTime? Statstidende { get; set; }
        [DisplayName("Partner Link")]
        public string? Partnerlink { get; set; }
              public Feallesbase()
        {

        }


    }
}

ASP.NETCoreIdentityCustom/Areas/Identity/Pages/Account/Create.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Bornholm_Sleagts.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;

namespace Bornholm_Sleagts.Areas.Identity.Pages.Account
{
    public class CreateModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserStore<ApplicationUser> _userStore;
        private readonly IUserEmailStore<ApplicationUser> _emailStore;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;

        public CreateModel(
            UserManager<ApplicationUser> userManager,
            IUserStore<ApplicationUser> userStore,
            SignInManager<ApplicationUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender)
        {
            _userManager = userManager;
            _userStore = userStore;
            _emailStore = GetEmailStore();
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Inputs { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrls { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        ///  
      
        public class InputModel
        {
            [Required]
            [StringLength(255, ErrorMessage = "The first name field should have a maximum of 255 characters")]
            [Display(Name = "Firstname")]
            public string FirstName { get; set; }

            [Required]
            [StringLength(255, ErrorMessage = "The last name field should have a maximum of 255 characters")]
            [Display(Name = "Lastname")]
            public string LastName { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }


        public async Task OnGetAsync(string returnUrl = null)
        {
            ReturnUrls = returnUrl;
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (ModelState.IsValid)
            {
                var user = CreateUser();


                user.FirstName = Inputs.FirstName;
                user.LastName = Inputs.LastName;

                await _userStore.SetUserNameAsync(user, Inputs.Email, CancellationToken.None);
                await _emailStore.SetEmailAsync(user, Inputs.Email, CancellationToken.None);
                var result = await _userManager.CreateAsync(user, Inputs.Password);

                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var userId = await _userManager.GetUserIdAsync(user);
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { area = "Identity", userId = userId, code = code, returnUrl = returnUrl },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Inputs.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    {
                        return RedirectToPage("RegisterConfirmation", new { email = Inputs.Email, returnUrl = returnUrl });
                    }
                    else
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return LocalRedirect(returnUrl);
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }

        private ApplicationUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<ApplicationUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(ApplicationUser)}'. " +
                    $"Ensure that '{nameof(ApplicationUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                    $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
            }
        }

        private IUserEmailStore<ApplicationUser> GetEmailStore()
        {
            if (!_userManager.SupportsUserEmail)
            {
                throw new NotSupportedException("The default UI requires a user store with email support.");
            }
            return (IUserEmailStore<ApplicationUser>)_userStore;
        }
    }
}

ASP.NETCoreIdentityCustom/Controllers/FeallesbaseController.cs
using Bornholm_Slægts.Models;
using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;
using EntityState = Microsoft.EntityFrameworkCore.EntityState;
using Microsoft.IdentityModel.Tokens;

using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

using String = System.String;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Bornholm_Sleagts.Areas.Identity.Data;
using Bornholm_Sleagts.Models;
using Microsoft.AspNetCore.Authorization;

namespace Bornholm_Slægts.Controllers
{
    public class FeallesbaseController : Controller
    {
        private readonly ApplicationDbContext _db;
        public FeallesbaseController(ApplicationDbContext db)
        {
            _db = db;
        }
        //[Authorize( "Admin")]
        [Authorize(Policy = "RequireManager")]
        public IActionResult Index(string? Firstname,DateTime? DoedDato, int pg = 1)
        {
           // ViewData["DateSortParm"] = Firstname == "DateTime" ? "Avisdato" : "DateTime";
            var objList = from b in _db.Feallesbases select b;
           
            if (!String.IsNullOrEmpty(Firstname) && DoedDato != null)
            {
                objList = objList.Where(b => b.Fornavne.Contains(Firstname) && b.Doedsdato == DoedDato);

            }
            else if (String.IsNullOrEmpty(Firstname) && DoedDato != null)
            {
                objList = objList.Where(b => b.Doedsdato == DoedDato);
            }
            else if (!String.IsNullOrEmpty(Firstname) && DoedDato == null)
            {
                objList = objList.Where(b => b.Fornavne.Contains(Firstname));
            }
            
            const int pageSize = 5;
            if (pg < 1)
            {
                pg = 1;
            }
            int recsCount = objList.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int resSkip = (pg - 1) * pageSize;
            var data = objList.Skip(resSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
          

            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if(id==0 || id == null)
            {
                return NotFound();

            }
            var obj = _db.Feallesbases.Find(id);
            if(obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }

        public IActionResult Update(int? ID)
        {
            if (ID == null || ID == 0)
            {
                return NotFound();
            }
            var obj = _db.Feallesbases.Find(ID);
            if(obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpGet]
        public IActionResult Search(DateTime DeadDate, string Firstname)
        {
            var objList = from b in _db.Feallesbases select b;
            if (DeadDate != null && Firstname == "")
            {
                objList = objList.Where(s => s.Doedsdato == (DeadDate));
                return View(objList);
            }

            else if (DeadDate == null && Firstname != "")

            {
                objList = objList.Where(s => s.Fornavne.Contains(Firstname));
                return View(objList);
            }else if(DeadDate !=null && Firstname !="" )
            {
                objList = objList.Where(s => s.Fornavne.Contains(Firstname) & s.Doedsdato==DeadDate);
                return View(objList);
            }
            return View("Index");

        }

        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Feallesbases.Find(id);
            if ( id==null || id==0)
            {
                return NotFound();
            }
           
            _db.Feallesbases.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "En annoncer sletet successfully";
            return RedirectToAction("Index");
        }
       
        [HttpGet]
        public IActionResult SearchGet(int? ID)
        {
            var obj = _db.Feallesbases.Find(ID);
            if (obj == null)
            {
                return NotFound();
            }
            
           if(obj==null)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Create(Feallesbase feallesbase)
        {
          
            if(ModelState.IsValid)
            {
                _db.Feallesbases.Add(feallesbase);
                _db.SaveChanges();
                TempData["success"] = "En annonccer tilføjet successfully";
                return RedirectToAction("Index");
            }
            return View();
           
        }
        [HttpPost]
        public IActionResult Update(Feallesbase feallesbase)
        {
          if(ModelState.IsValid)
            {
                _db.Entry(feallesbase).State = EntityState.Modified;
                _db.SaveChanges();
                TempData["success"] = "Anoncer Redigere successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

ASP.NETCoreIdentityCustom/Views/Feallesbase/Create.cshtml
@model Bornholm_Slægts.Models.Feallesbase
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-black-50 pl-3">Tilføj Døds Annoncer</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
<form method="post" asp-action="Create">
    <div class=" border p-3">
        <div class="form-group row text-center">
            
        </div>
        <div class="col">
            <div class="row-12">
                <div class="form-group col">
                    <div asp-validation-summary="All"></div>
                    <div class="mp-3">
                        <label asp-for="AvisTypeID" class="form-label"></label>
                        <input asp-for="AvisTypeID" class="form-control" />
                        <span asp-validation-for="AvisTypeID" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Avisdato" class="form-label"></label>
                        <input asp-for="Avisdato" class="form-control" />
                        <span asp-validation-for="Avisdato" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Efternavn" class="form-label"></label>
                        <input asp-for="Efternavn" class="form-control" />
                        <span asp-validation-for="Efternavn" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Fornavne" class="form-label"></label>
                        <input asp-for="Fornavne" class="form-control" />
                        <span asp-validation-for="Fornavne" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Foedt" class="form-label"></label>
                        <input asp-for="Foedt" class="form-control" />
                        <span asp-validation-for="Foedt" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Alder" class="form-label"></label>
                        <input asp-for="Alder" class="form-control" />
                        <span asp-validation-for="Alder" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Doebenavn" class="form-label"></label>
                        <input asp-for="Doebenavn" class="form-control" />
                        <span asp-validation-for="Doebenavn" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Erhverv" class="form-label"></label>
                        <input asp-for="Erhverv" class="form-control" />
                       <span asp-validation-for="Erhverv" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Adresser" class="form-label"></label>
                        <input asp-for="Adresser" class="form-control" />
                        <span asp-validation-for="Adresser" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="SognID" class="form-label"></label>
                        <input asp-for="SognID" class="form-control" />
                        <span asp-validation-for="SognID" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="TidlBopael" class="form-label"></label>
                        <input asp-for="TidlBopael" class="form-control" />
                        <span asp-validation-for="TidlBopael" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Doedsdato" class="form-label"></label>
                        <input asp-for="Doedsdato" class="form-control" />
                        <span asp-validation-for="Doedsdato" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Begravelsesdato" class="form-label"></label>
                        <input asp-for="Begravelsesdato" class="form-control" />
                        <span asp-validation-for="Begravelsesdato" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Begravelsessted" class="form-label"></label>
                        <input asp-for="Begravelsessted" class="form-control" />
                        <span asp-validation-for="Begravelsessted" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Efterladte" class="form-label"></label>
                        <input asp-for="Efterladte" class="form-control" />
                        <span asp-validation-for="Efterladte" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="FlereDoedsannoncer" class="form-label"></label>
                        <input asp-for="FlereDoedsannoncer" class="form-control" />
                        <span asp-validation-for="FlereDoedsannoncer" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="AndreDataFraAnnoncen" class="form-label"></label>
                        <input asp-for="AndreDataFraAnnoncen" class="form-control" />
                        <span asp-validation-for="AndreDataFraAnnoncen" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Oegenavne" class="form-label"></label>
                        <input asp-for="Oegenavne" class="form-control" />
                        <span asp-validation-for="Oegenavne" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Nekrolog" class="form-label"></label>
                        <input asp-for="Nekrolog" class="form-control" />
                        <span asp-validation-for="Nekrolog" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Mindeord" class="form-label"></label>
                        <input asp-for="Mindeord" class="form-control" />
                        <span asp-validation-for="Mindeord" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Statstidende" class="form-label"></label>
                        <input asp-for="Statstidende" class="form-control" />
                        <span asp-validation-for="Statstidende" class="text-danger"></span>
                    </div>
                    <div class="mp-3">
                        <label asp-for="Partnerlink" class="form-label"></label>
                        <input asp-for="Partnerlink" class="form-control" />
                        <span asp-validation-for="Partnerlink" class="text-danger"></span>
                    </div>
                </div>
               <br/>
                <div class="row">
                        <div class="col-6 col-md-3">
                       
                            <input type="submit" class="btn btn-primary w-75" value="Tilføj" />
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-action="Index" class="btn btn-primary w-75">Tilbage</a>
                        </div>
                    
                </div>

            </div>
        </div>
    </div>
</form>
</div>
</div>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}
<br/>

ASP.NETCoreIdentityCustom/Views/Feallesbase/Index.cshtml
@model IEnumerable<Bornholm_Slægts.Models.Feallesbase> 
@{
    ViewData["Title"] = "Index";
    Pager pager = new Pager();
    int pageNo = 0;
    if(ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-black-50 pl-3">Liste Døds Annoncer</h2>
            </div>
        </div>
    </div>

    <div class="row pt-4">
        <div class="col-4 text-right">
            <a asp-controller="Feallesbase" asp-action="Create" class="btn btn-primary w-50"><i class="bi bi-plus-circle-fill"></i>  Tilføj Ny</a>
        </div>
        <div class="col-4 text-">
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary w-50"><i class="bi bi-backspace"></i>  Tilbage</a>
        </div>
    </div>

    <hr/>
  <form asp-controller="Feallesbase" asp-action="Index">
    <div>
        Fornavne: <input type="text" name="Firstname" />
        DeodsDato: <input type="datetime" name="DoedDato" />
        <input type="submit" value="Søg" />
         <a asp-action="Index" class="btn btn-primary w-20"><i class="bi bi-backspace"></i>  Tilbage til fuld liste</a>
    </div>
  </form>
    <hr />
    <br />

    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">
            @if (pager.CurrentPage > 1)
            {
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@(pager.CurrentPage-1)">Previouse</a>
                </li>
            }
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage? "active":"")">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }
            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                </li>
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }

 

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" >
            <thead>
                <tr>
                    <th> ID</th>
                    <th> AvisTypeID </th>
                     <th>Avisdato</th>
                    <th> Efternavn </th>
                    <th> Fornavne</th>
                    <th>Foedt</th>
                    <th>Alder</th>
                    <th>Doebenavn</th>
                    <th>Erhverv</th>
                    <th>Adresser</th>
                    <th> SognID </th>
                    <th>TidlBopael </th>
                    <th>Doedsdato </th>
                    <th> Begravelsesdato </th>
                    <th> Begravelsessted</th>
                    <th>Efterladte</th>
                    <th>FlereDoedsannoncer </th>
                    <th>AndreDataFraAnnoncen </th>
                    <th>Oegenavne </th>
                    <th> Nekrolog </th>
                    <th> Mindeord </th>
                    <th> Statstidende </th>
                    <th> Partnerlink </th>
                    <th>Redigere</th>
                    <th>Slet</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderBy(m=>m.Foedt))
                {
                    <tr>
                        <td width="5%">@item.ID</td>
                        <td width="5%">@item.AvisTypeID</td>
                        <td width="5%">@item.Avisdato</td>
                        <td width="5%">@item.Efternavn</td>
                        <td width="5%">@item.Fornavne</td>
                        <td width="5%">@item.Foedt</td>
                        <td width="5%">@item.Alder</td>
                        <td width="5%">@item.Doebenavn</td>
                        <td width="5%">@item.Erhverv</td>
                        <td width="5%">@item.Adresser</td>
                        <td width="5%">@item.SognID</td>
                        <td width="5%">@item.TidlBopael</td>
                        <td width="5%">@item.Doedsdato</td>
                        <td width="5%">@item.Begravelsesdato</td>
                        <td width="5%">@item.Begravelsessted</td>
                        <td width="5%">@item.Efterladte</td>
                        <td width="5%">@item.FlereDoedsannoncer</td>
                        <td width="5%">@item.AndreDataFraAnnoncen</td>
                        <td width="5%">@item.Oegenavne</td>
                        <td width="5%">@item.Nekrolog</td>
                        <td width="5%">@item.Mindeord</td>
                        <td width="5%">@item.Statstidende</td>
                        <td width="5%">@item.Partnerlink</td>
                        
                        <td>
                            <div class=" btn-group" role="group">
                         
                                <a asp-controller="Feallesbase" asp-action="Update" asp-route-id="@item.ID" class="btn btn-primary  mx-2"><i class="bi bi-pencil-square"></i>Redigere</a>
                                </div>
                        </td>
                         <td>
                            <div>
                                <a asp-controller="Feallesbase" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger  mx-1"><i class="bi bi-trash3"></i>Slet</a>
                            </div>
                         </td>
                        
                    </tr>
                }

            </tbody>
        </table>
    }
    else
    {
        <p>Ingen elementer oprettet endnu</p>
    }

 
     @if(pager.TotalPages>0)
     {
        <ul class="pagination justify-content-end">
             @if(pager.CurrentPage> 1)
             {
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@(pager.CurrentPage-1)">Previouse</a>
                </li>
             }
           @for(var pge = pager.StartPage; pge<= pager.EndPage; pge++)
           {
            <li class="page-item @(pge == pager.CurrentPage? "active":"")">
                <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@pge">@pge</a>
            </li>    
           }
            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                </li>
                <li class="page-item ">
                    <a class="page-link" asp-controller="Feallesbase" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }
        </ul>
     }
 <br/>

  
 
 
 